# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GameOfLife(object):
    def setupUi(self, GameOfLife):
        GameOfLife.setObjectName("GameOfLife")
        GameOfLife.resize(618, 750)
        self.centralwidget = QtWidgets.QWidget(GameOfLife)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setObjectName("frame")
        self.boardLayout = QtWidgets.QGridLayout(self.frame)
        self.boardLayout.setObjectName("boardLayout")
        self.verticalLayout.addWidget(self.frame)
        self.buttonWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.buttonWidget.sizePolicy().hasHeightForWidth())
        self.buttonWidget.setSizePolicy(sizePolicy)
        self.buttonWidget.setObjectName("buttonWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.buttonWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.buttonWidget)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.reset = QtWidgets.QPushButton(self.widget)
        self.reset.setObjectName("reset")
        self.gridLayout_2.addWidget(self.reset, 1, 0, 1, 1)
        self.play = QtWidgets.QPushButton(self.widget)
        self.play.setObjectName("play")
        self.gridLayout_2.addWidget(self.play, 1, 1, 1, 1)
        self.singleStep = QtWidgets.QPushButton(self.widget)
        self.singleStep.setObjectName("singleStep")
        self.gridLayout_2.addWidget(self.singleStep, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.buttonWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.speedLabel = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.speedLabel.setFont(font)
        self.speedLabel.setObjectName("speedLabel")
        self.verticalLayout_2.addWidget(self.speedLabel)
        self.sliderSpeed = QtWidgets.QSlider(self.widget_2)
        self.sliderSpeed.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSpeed.setObjectName("sliderSpeed")
        self.verticalLayout_2.addWidget(self.sliderSpeed)
        self.gridLayout.addWidget(self.widget_2, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.buttonWidget)
        GameOfLife.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GameOfLife)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 618, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        GameOfLife.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GameOfLife)
        self.statusbar.setObjectName("statusbar")
        GameOfLife.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(GameOfLife)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(GameOfLife)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtWidgets.QAction(GameOfLife)
        self.actionQuit.setObjectName("actionQuit")
        self.actionRules = QtWidgets.QAction(GameOfLife)
        self.actionRules.setObjectName("actionRules")
        self.actionAbout = QtWidgets.QAction(GameOfLife)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionRules)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(GameOfLife)
        QtCore.QMetaObject.connectSlotsByName(GameOfLife)

    def retranslateUi(self, GameOfLife):
        _translate = QtCore.QCoreApplication.translate
        GameOfLife.setWindowTitle(_translate("GameOfLife", "Conoway\'s Game of Life"))
        self.label.setText(_translate("GameOfLife", "Controls"))
        self.reset.setText(_translate("GameOfLife", "Reset"))
        self.play.setText(_translate("GameOfLife", "Play"))
        self.singleStep.setText(_translate("GameOfLife", "Single Step"))
        self.speedLabel.setText(_translate("GameOfLife", "Speed: #"))
        self.menuFile.setTitle(_translate("GameOfLife", "File"))
        self.menuHelp.setTitle(_translate("GameOfLife", "Help"))
        self.actionLoad.setText(_translate("GameOfLife", "Load"))
        self.actionSave.setText(_translate("GameOfLife", "Save"))
        self.actionQuit.setText(_translate("GameOfLife", "Quit"))
        self.actionRules.setText(_translate("GameOfLife", "Rules"))
        self.actionAbout.setText(_translate("GameOfLife", "About"))

